### ISSUE TITLE
Warning: ignoring input sourcemap...

### ISSUE THREAD

**Issue by miguelcobain** [bustle/ember-mobiledoc-dom-renderer#27]
I get the following warning when using the addon:

`Warning: ignoring input sourcemap for vendor/mobiledoc-dom-renderer/amd/mobiledoc-dom-renderer.js because ENOENT: no such file or directory, open '/Users/miguel/workspace/my-project/tmp/source_map_concat-input_base_path-qnSayqBD.tmp/0/vendor/mobiledoc-dom-renderer/amd/mobiledoc-dom-renderer.map'`

Related with https://github.com/bustlelabs/ember-mobiledoc-editor/issues/19

This warning can be seen in ember-mobiledoc-editor builds as well: https://travis-ci.org/bustlelabs/ember-mobiledoc-editor/jobs/176482141

**Comment by josemarluedke** [comment]
I'm seeing this as well.  Didn't someone solved this problem already?

**Comment by lukemelia** [comment]
This doesn't appear to be happening on more recent builds. Closing -- free free to reopen if you are seeing this.
